project = 'ServSafe Manager Exam Prep Reference'
copyright = '2026, FoodSafe Prep'
author = 'FoodSafe Prep'
release = '1.0'
extensions = []
templates_path = ['_templates']
exclude_patterns = ['_build']
html_theme = 'sphinx_rtd_theme'
html_baseurl = 'https://servsafe-docs.readthedocs.io/'
